// Generated by prisma/postgenerate.ts

import type { Insertable, Selectable, Updateable } from 'kysely'
import type { Comment as DBComment,CommentVote as DBCommentVote,Key as DBKey,Place as DBPlace,Post as DBPost,Session as DBSession,Subscription as DBSubscription,User as DBUser,Vote as DBVote } from './schema'
    
export type Comment = Selectable<DBComment>
export type NewComment = Insertable<DBComment>
export type UpdateComment = Updateable<DBComment>
        
export type CommentVote = Selectable<DBCommentVote>
export type NewCommentVote = Insertable<DBCommentVote>
export type UpdateCommentVote = Updateable<DBCommentVote>
        
export type Key = Selectable<DBKey>
export type NewKey = Insertable<DBKey>
export type UpdateKey = Updateable<DBKey>
        
export type Place = Selectable<DBPlace>
export type NewPlace = Insertable<DBPlace>
export type UpdatePlace = Updateable<DBPlace>
        
export type Post = Selectable<DBPost>
export type NewPost = Insertable<DBPost>
export type UpdatePost = Updateable<DBPost>
        
export type Session = Selectable<DBSession>
export type NewSession = Insertable<DBSession>
export type UpdateSession = Updateable<DBSession>
        
export type Subscription = Selectable<DBSubscription>
export type NewSubscription = Insertable<DBSubscription>
export type UpdateSubscription = Updateable<DBSubscription>
        
export type User = Selectable<DBUser>
export type NewUser = Insertable<DBUser>
export type UpdateUser = Updateable<DBUser>
        
export type Vote = Selectable<DBVote>
export type NewVote = Insertable<DBVote>
export type UpdateVote = Updateable<DBVote>
        